#!/bin/sh

set -e

case "$1" in

  configure)
    cd /opt/telegram/
    tar -xvf telegram.tar.xz
    mv ./Telegram/Telegram ./telegram
    rm -rf ./Telegram
    rm -rf telegram.tar.xz
    mv Telegram.sh Telegram
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac



exit 0
